package graderobjects;

public enum InvalidationReason
{
    INVALID_EMAIL_ACCESS_DENIED,
    TIME_LIMIT_VIOLATION,
    SUBJECT_MISSING,
    SUBJECT_INVALID,
    SUBMISSION_COUNT_EXCEEDED,
    FOREIGN_PROGRAMMING_LANG,
    INVALID_JAVA_CLASS_NAME,
    INVALID_SRC_FILE_NAME,
    COMPILE_ERROR
}
